// Typed access to the compiled world (data/world.json), generated by
// scripts/compile-world.ts from content/**/*.json. Run `npm run compile:world`
// after editing content/ to regenerate it before this module picks up changes.

import worldData from "../../data/world.json" with { type: "json" };
import { buildWorldGraph, getRecommendedPath } from "./world-graph.js";
import type { DistrictNode, GraphEdge, GraphWarning, GraphWarningKind, WorldGraph } from "./world-graph.js";

export interface District {
  id: string;
  type: "district";
  name: string;
  slug: string;
  status: "locked" | "open" | "in-progress";
  guardianId?: string;
  subtitle?: string;
  description?: string;
  dataSources?: Array<{ type: "github" | "obsidian" | "manual"; owner?: string; vaultPath?: string }>;
  connections?: string[];
}

export interface Guardian {
  id: string;
  type: "guardian";
  name: string;
  title: string;
  districtId: string;
  quote?: string;
  knowledge?: string[];
}

export interface Repository {
  id: string;
  type: "repository";
  githubRepository: string;
  treeName: string;
  districtId: string;
  story?: string;
  technologies?: string[];
  skillIds?: string[];
}

export interface Project {
  id: string;
  type: "project";
  name: string;
  status: "planned" | "in-progress" | "completed";
  description?: string;
  districtId?: string;
  repositoryId?: string;
  technologies?: string[];
  skillIds?: string[];
  links?: Array<{ label: string; url: string }>;
}

export interface Quest {
  id: string;
  type: "quest";
  name: string;
  status: "locked" | "available" | "completed";
  description?: string;
  districtId?: string;
  objectives?: string[];
  rewardSkillIds?: string[];
}

export interface Note {
  id: string;
  type: "note";
  slug: string;
  title: string;
  summary: string;
  category: "linux" | "networking" | "cloud" | "automation" | "security" | "kubernetes" | "projects" | "career";
  body: string;
  published: boolean;
  updatedAt: string;
  districtId: string;
  tags?: string[];
  relatedSkillIds?: string[];
  relatedRepositoryIds?: string[];
  relatedNoteIds?: string[];
  source?: string;
  order?: number;
}

export interface Skill {
  id: string;
  type: "skill";
  name: string;
  description?: string;
  category?: string;
}

export interface Certification {
  id: string;
  type: "certification";
  name: string;
  issuer: string;
  dateEarned?: string;
  credentialUrl?: string;
  districtId?: string;
  skillIds?: string[];
}

export interface Profile {
  id: string;
  type: "profile";
  name: string;
  title?: string;
  tagline?: string;
  email?: string;
  linkedin?: string;
  website?: string;
  location?: string;
  links?: Array<{ label: string; url: string }>;
}

export interface Experience {
  id: string;
  type: "experience";
  employer: string;
  role: string;
  startDate: string;
  summary: string;
  endDate?: string;
  current?: boolean;
  location?: string;
  order?: number;
  highlights?: string[];
  skillIds?: string[];
  links?: Array<{ label: string; url: string }>;
  districtId?: string;
}

export interface World {
  meta: { generatedAt: string; sourceFileCount: number; entityCount: number };
  districts: District[];
  guardians: Guardian[];
  repositories: Repository[];
  projects: Project[];
  quests: Quest[];
  notes: Note[];
  skills: Skill[];
  certifications: Certification[];
  profiles: Profile[];
  experiences: Experience[];
}

export const world = worldData as unknown as World;

function indexBy<T extends { id: string }>(items: T[]): Map<string, T> {
  return new Map(items.map((item) => [item.id, item]));
}

const districtsById = indexBy(world.districts);
const guardiansById = indexBy(world.guardians);
const repositoriesById = indexBy(world.repositories);
const projectsById = indexBy(world.projects);
const questsById = indexBy(world.quests);
const notesById = indexBy(world.notes);
const skillsById = indexBy(world.skills);
const certificationsById = indexBy(world.certifications);
const experiencesById = indexBy(world.experiences);

export const getDistrict = (id: string): District | undefined => districtsById.get(id);
export const getGuardian = (id: string): Guardian | undefined => guardiansById.get(id);
export const getRepository = (id: string): Repository | undefined => repositoriesById.get(id);
export const getProject = (id: string): Project | undefined => projectsById.get(id);
export const getQuest = (id: string): Quest | undefined => questsById.get(id);
export const getNote = (id: string): Note | undefined => notesById.get(id);
export const getSkill = (id: string): Skill | undefined => skillsById.get(id);
export const getCertification = (id: string): Certification | undefined => certificationsById.get(id);
export const getExperience = (id: string): Experience | undefined => experiencesById.get(id);

export const listDistricts = (): District[] => world.districts;

export const getGuardianForDistrict = (districtId: string): Guardian | undefined =>
  world.guardians.find((guardian) => guardian.districtId === districtId);

export const getRepositoriesForDistrict = (districtId: string): Repository[] =>
  world.repositories.filter((repository) => repository.districtId === districtId);

export const getConnectedDistricts = (districtId: string): District[] =>
  (getDistrict(districtId)?.connections ?? []).map(getDistrict).filter((d): d is District => d !== undefined);

/** The single place a district's Valley URL is built — DistrictCard and
 * Mission Brief's "Explore the World" handoff both call this rather than
 * each constructing "/valley/..." themselves. */
export const getDistrictPath = (district: Pick<District, "slug">): string => `/valley/${district.slug}`;

export const getProfile = (): Profile | undefined => world.profiles[0];

export const getExperiencesForSkill = (skillId: string): Experience[] =>
  world.experiences.filter((experience) => experience.skillIds?.includes(skillId));

export const getCertificationsForSkill = (skillId: string): Certification[] =>
  world.certifications.filter((certification) => certification.skillIds?.includes(skillId));

export const getRepositoriesForSkill = (skillId: string): Repository[] =>
  world.repositories.filter((repository) => repository.skillIds?.includes(skillId));

export const getProjectsForSkill = (skillId: string): Project[] =>
  world.projects.filter((project) => project.skillIds?.includes(skillId));

export { buildWorldGraph, getRecommendedPath };
export type { DistrictNode, GraphEdge, GraphWarning, GraphWarningKind, WorldGraph };

export const worldGraph: WorldGraph = buildWorldGraph(world);
